# Generated by Django 4.0.2 on 2022-02-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ManyToManyField(related_name='instructor', to='users.UserProfile'),
        ),
    ]
