# Generated by Django 4.0.2 on 2022-02-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_directmessagethread_directmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
