# Generated by Django 4.0.2 on 2022-03-04 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profilesettings_userprofile_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='settings',
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='show_about',
            field=models.BooleanField(default=True),
        ),
    ]
