# Generated by Django 4.0.2 on 2022-03-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_directmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumroom',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
